name: run java git diff

on:
  push:
    branches:
      - main-close
  pull_request:
    branches:
      - main-close

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: set up jdk11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: run java code
        run: |
          cd deepseek-code-review-sdk/src/main/java
          javac com/bugstack/middleware/sdk/DeepSeekCodeReview.java
          java com.bugstack.middleware.sdk.DeepSeekCodeReview
