name: maven-jar.yaml
on:
  push:
    - *
  pull_request:
    - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 建议升级到最新版

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy Jar
        run: mvn dependency:copy -Dartifact=com.bugstack:deepseek-code-review:1.0 -DoutputDirectory=./libs

      - name: Run Code Review
        run: java -jar ./libs/deepseek-code-review-sdk-1.0.jar