name: maven-jar.yaml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy Jar
        run: mvn dependency:copy -Dartifact=com.bugstack:deepseek-code-review-sdk:1.0 -DoutputDirectory=./libs

      - name: Run Code Review
        run: java -jar ./libs/deepseek-code-review-sdk-1.0.jar